name: capybara_aloha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GOOGLE
  google_fonts: ^3.0.1

  # GET
  get: 4.6.5

  # OTHRES
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  flutter_screenutil: 5.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

